"""add is_edited column to discussion_posts

Revision ID: 21d4e918516e
Revises: 1c20c3e51d9e
Create Date: 2026-04-18 12:48:07.704454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d4e918516e'
down_revision = '1c20c3e51d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
