"""add member_a tables

Revision ID: 7d231b2f0d69
Revises: 457093f030d4
Create Date: 2026-09-21 15:54:36.206634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d231b2f0d69'
down_revision = '457093f030d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=True),
    sa.Column('consent_status', sa.String(length=20), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elderly_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('family_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('device_uuid', sa.String(length=120), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_uuid')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('family_elderly_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_user_id', sa.Integer(), nullable=False),
    sa.Column('elderly_profile_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elderly_profile_id'], ['elderly_profiles.id'], ),
    sa.ForeignKeyConstraint(['family_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discussion_posts_edited_by_id_users'), type_='foreignkey')
        batch_op.drop_column('edited_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_by_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discussion_posts_edited_by_id_users'), 'users', ['edited_by_id'], ['id'])

    op.drop_table('family_elderly_links')
    op.drop_table('user_settings')
    op.drop_table('user_devices')
    op.drop_table('family_contacts')
    op.drop_table('elderly_profiles')
    op.drop_table('consent_records')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
